export const environment = {
  production: true,
  OCR_LICENSE:
    'QUVTAgAAAGzINdTc96gA4Y9ZPxP2IBV6Oe8oxFBtsMkubyhcOMw8W1Dckd3AG24OfabMFlKTmk6cVA2Ii5lZPMdM7dvpbGDYP2YdrYX205pwodJX+gOWgb73Fu6A1v1433jbzy7s8eqBbPqFEBb4H+M1HSQtle0EajqHC67MZ53S5WhqLmWTxMKVYgdizqw6TCxUtoeJSmI=',
  IDENTY_API_BASE_URL: 'http://localhost:3000/api',
  IDENTY_SECURITY_LEVEL_FACE: 'VERY_HIGH',
  MAX_ATTEMPTS_BIO: 5,
  BIO_BYPASS_CUI: true,
  IDENTY_SECURITY_MATCH_FACE: 'HIGH',
};
